name: CI

on: [push, pull_request]

env:
  GO_VERSION: '1.22'

jobs:
  bsd:
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.1'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CI script on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            case "$(uname)" in
              FreeBSD)
                sudo pkg install -y go
                ;;
              NetBSD)
                sudo pkgin -y install go

                for bin in /usr/pkg/bin/go1*; do
                  src=$bin
                done
                sudo ln -s "$src" /usr/pkg/bin/go
                ;;
              OpenBSD)
                sudo pkg_add -I go
                ;;
            esac
            PATH=$(go env GOPATH)/bin:$PATH

            go build
            ./process-env process-env HOME USER

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build and run
      run: |
        go build
        ./process-env process-env

  windows:
    runs-on: windows-latest
    steps:
    - name: 'Disable `autocrlf` in Git'
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build and run
      run: |
        go build
        .\process-env.exe process-env.exe --json USERNAME USERPROFILE
